import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>PROOF OF CONCEPT: SQL GRADER</h1>
        </div>
        <div>
          <Link href="/question/q1"><button>Q1</button></Link>
          <Link href="/question/q2"><button>Q2</button></Link>
        </div>
      </main>
    </>
  )
}
